-- Migrate all TIMESTAMP WITHOUT TIME ZONE columns to TIMESTAMP WITH TIME ZONE.
-- Existing values are already UTC (written by the JVM with ZoneOffset.UTC), so Postgres
-- interprets them as UTC during the implicit cast — no data is shifted.

ALTER TABLE institutes
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE users
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE teacher_details
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE student_details
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE courses
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE subjects
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE chapters
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE topics
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE questions
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE options
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE batches
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE student_enrollments
    ALTER COLUMN enrolled_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE leads
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE tests
    ALTER COLUMN available_from  TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN available_until TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN created_at      TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN updated_at      TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE test_questions
    ALTER COLUMN added_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE test_assignments
    ALTER COLUMN available_from  TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN available_until TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN assigned_at     TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE test_attempts
    ALTER COLUMN started_at   TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN submitted_at TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN expires_at   TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE test_attempt_answers
    ALTER COLUMN answered_at TYPE TIMESTAMP WITH TIME ZONE;
